### ISSUE TITLE
Compatibility matrix

### ISSUE THREAD

**Issue by timonzi** [quarkiverse/quarkus-artemis#249] opened 2023-07-21 11:05 UTC
Hello,

I wonder how to determine which Quarkus Artemis extension version is compatible with which Quarkus version!?
Is there a compatibility matrix which I don't know?

I refer here to the [comment from @gsmet](https://github.com/quarkiverse/quarkus-artemis/issues/24#issuecomment-1026955217):

> For all the Quarkiverse extensions, the rule of thumb is that we release a new version either when we have new features we want to publish or **when there is a compatibility issue** [...]

I assume, that when a new extension version is provided, I have to use it when I update the Quarkus version.
But how can I see for example which version is compatible with Quarkus 2.16.8.Final or any other older release?

**Comment by turing85** [comment] 2023-07-21 11:07
Please see point 4 of https://github.com/quarkiverse/quarkus-artemis/issues/248

**Comment by turing85** [comment] 2023-07-21 11:08
Closed as duplicate of https://github.com/quarkiverse/quarkus-artemis/issues/248

**Closed by turing85** 2023-07-21 11:08 UTC
Labels: duplicate
