### ISSUE TITLE
Question: Release notes

### ISSUE THREAD

**Issue by timonzi** [quarkiverse/quarkus-artemis#90] opened 2022-10-28 12:00 UTC
Hello,

I don't find any documentation about changes in the releases. Are there any release notes?
For us it is important to know for example when the Artemis version was changed (which of course can be found in the pom.xml) and of course when there are breaking changes. For example as far as I understood the release version 2.0.0 was created, because of changes in the config. But what are those changes?
After I switched to the latest version, our tests no longer work. Now I wonder if there is a change I could/should have noticed via release notes.

**Comment by turing85** [comment] 2022-10-28 17:09
Hi!
we have currently no release notes.

To you first question: The version of artemis was bumped from `2.25.0` to `2.26.0` on 2022-09-27 and released with release `1.3.0`.

As for the config-changes: we aligned the configuration options with the ones of `dataSources`. this was done during the ingetration of named configurations:
- `quarkus.artemis.health.enabled` to enable health checking for artemis
- `quarkus.artemis.health-exclude` and `quarkus.artemis."named-connection".health-exclude` to exclude specific connections from health checking
- `quarkus.artemis.xa-enabled` and `quarkus.artemis."named-connection".xa-enabled` to activate XA transactions (beign in line with `quarkus.artemis.health-exclude`).

So the main breaking change here is that `...xa.enabled` is no longer valid, and should now be written as `...xa-enabled`

**Comment by turing85** [comment] 2022-10-28 19:19
Update: I have created some documentation improvements, they are up for review. As soon as they are merged, we'll write notes for release `2.0.0`. Sorry for the inconvenience. We will take care of doing things "in the right order" in future releases.

**Comment by turing85** [comment] 2022-10-28 19:27
Update #2: In the meantime, here are the release notes for `1.3.0`: https://github.com/quarkiverse/quarkus-artemis/releases/tag/1.3.0

**Comment by middagj** [comment] 2022-10-30 16:06
> After I switched to the latest version, our tests no longer work. Now I wonder if there is a change I could/should have noticed via release notes.

On a separate topic did you find out why your tests were no longer working? Perhaps we overlooked a use case, interested to know about it.

**Comment by turing85** [comment] 2022-10-31 12:10
Release notes for [`2.0.0`](https://github.com/quarkiverse/quarkus-artemis/releases/tag/2.0.0). The documentation site should update within the next 6 hours.

**Comment by timonzi** [comment] 2022-11-02 08:27
Sorry for the late reply, I was on vacation.

First of all, thank you very much for the release notes! I think they can/will be a great help, especially in case of breaking changes.

Regarding my failed tests: I didn't have time to investigate the issues. I will catch up today and give you feedback.

**Comment by timonzi** [comment] 2022-11-02 09:11
Not sure at this moment, but I think the problem is that the property _quarkus.artemis.url_ seems to be fixed at build time.
But the [documentation](https://quarkiverse.github.io/quarkiverse-docs/quarkus-artemis/dev/index.html#quarkus-artemis-core_quarkus.artemis.url) does not show it as such.

At least I get the following warning:
```
2022-11-02 10:10:40.251 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.artemis.url is set to 'tcp://localhost:49193' but it is build time fixed to 'tcp://127.0.0.1:61616'. Did you change the property quarkus.artemis.url after building the application?
```

We use an own Artemis test resource (container), where we map the automatically chosen port to the property (including the host of course). When I start a container with the port defined in the application.properties (61616), the tests work again.

**Comment by zhfeng** [comment] 2022-11-02 14:23
It's weird. I think `quarkus.artemis.url` can be override at runtime.

**Comment by timonzi** [comment] 2022-11-02 14:57
> It's weird. I think `quarkus.artemis.url` can be override at runtime.

This was the case until we switched to release 2.0.0 (for testing purpose).
Maybe it is somehow related to https://github.com/quarkiverse/quarkus-artemis/issues/36 ?

**Comment by timonzi** [comment] 2022-11-02 15:05
It happens in JVM mode

**Comment by turing85** [comment] 2022-11-02 16:16
This could be a side-effect due to the fact how we determine the connections at compile-time (i.e. the [`ShadowRunTimeConfig`](https://github.com/quarkiverse/quarkus-artemis/blob/main/core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ShadowRunTimeConfigs.java)). I'll double-check and report back.

**Comment by turing85** [comment] 2022-11-02 16:42
I cannot reproduce the behaviour. My setup:
- in `application.properties`: `quarkus.artemis.url=${ARTEMIS_URL:tcp://dummy:61616}`
- start artemis throuhg 'docker-compose`, expose it on `localhost:61616`
- `export ARTEMIS_URL=tcp://localhost:61616`, `java -jar quarkus-run.jar`
- access `localhost:8080/q/health`, all connections are up

@timonzi what version are you using? `2.0.0`? Could you provide a reproducer?

**Comment by timonzi** [comment] 2022-11-02 17:26
> @timonzi Could you provide a reproducer?

I will try to provide an example tomorrow.

**Comment by turing85** [comment] 2022-11-02 17:28
On a related note: @zhfeng do you remember what the initial decidion was to not start `devservices` if a `url` is present?

**Comment by turing85** [comment] 2022-11-02 18:44
@timonzi correction: I can reproduce the problem. And yes, it is related to the [`ShadowRunTimeConfig`](https://github.com/quarkiverse/quarkus-artemis/blob/main/core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ShadowRunTimeConfigs.java)). Baseline is: If we set a value, it is fixed at compile-time. If we just set a variable (like `quarkus.artemis.url=${ARTEMIS_URL}` and override it at compile-time, it works. We are working on a solution.

**Comment by zhfeng** [comment] 2022-11-03 02:44
@turing85 did you find a way to sort it out? I just add two comments on your above commit.

**Comment by zhfeng** [comment] 2022-11-03 02:44
@turing85 did you find a way to sort it out? I just add two comments on your above commit.

**Comment by turing85** [comment] 2022-11-03 10:34
@zhfeng Yes, I think so. I also answered your comments. Those are the shadows of the ÀrtemisRuntimeConfigs`, therefore `Shadow*Runitme*Config`

**Comment by turing85** [comment] 2022-11-03 10:35
@timonzi I released version `2.0.1.CR1`. this one will still produce the warning, however the property should work as expected now. We will have a section in the documetation about that.

**Comment by zhfeng** [comment] 2022-11-03 10:39
Did you check it with native mode?

**Comment by turing85** [comment] 2022-11-03 10:48
Yes. And we have new dedicated tests for this case ([here](https://github.com/quarkiverse/quarkus-artemis/tree/feature/90-fix-prpoerty-bind-at-runtime/integration-tests/core/with-default-change-url) and [here](https://github.com/quarkiverse/quarkus-artemis/tree/feature/90-fix-prpoerty-bind-at-runtime/integration-tests/jms/with-default-change-url)). The tests produce the warnings reported by @timonzi, but the semanitc is correct.

**Comment by zhfeng** [comment] 2022-11-03 11:18
Hi @turing85 
I just take a deep look at your changes. So

- [ArtemisRuntimeConfigs](https://github.com/quarkiverse/quarkus-artemis/blob/2fe3027dd1711b767190edc83d7e18c79a166b8a/core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisRuntimeConfigs.java)(phase = ConfigPhase.RUN_TIME) it should be avaliable at runtime which includes `quarkus.artemis.url` property
- [ShadowRunTimeConfigs](https://github.com/quarkiverse/quarkus-artemis/blob/2fe3027dd1711b767190edc83d7e18c79a166b8a/core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ShadowRunTimeConfigs.java)(phase = ConfigPhase.BUILD_TIME) it should be avaliable only at buildtime which also includes `quarkus.artemis.url` property

I wonder if this property `quarkus.artemis.url` is confilict?

**Comment by zhfeng** [comment] 2022-11-03 11:20
It confuse me.

**Comment by turing85** [comment] 2022-11-03 11:29
@zhfeng If you are interested: I opened a [feature request](https://github.com/quarkusio/quarkus/issues/28415) to read configuration keys at compile-time, but it was closed as "not planned".

**Comment by timonzi** [comment] 2022-11-03 11:33
> @timonzi I released version `2.0.1.CR1`. this one will still produce the warning, however the property should work as expected now. We will have a section in the documetation about that.

Using the new version the tests run again successfully. As you wrote, the warning is still present.

**Comment by turing85** [comment] 2022-11-03 11:40
@timonzi good to hear! I will prepare the `2.0.1` release.

**Comment by zhfeng** [comment] 2022-11-03 11:57
Thanks a lot @turing85 and now it is much clearer. I can understand the motivation to have `ShadowRuntimeConfigs` at build time. Good job!

Is there any chance to improve it on Quarkus side as David mentioned in the discussion? I think it is worthy to open an issue on quarkus.

**Comment by middagj** [comment] 2022-11-03 12:11
If we fix it in Quarkus we still have the use the old way if we want to support older versions of Quarkus.

What if we make `enabled` for all named configurations mandatory and use the same approach as DataSource? I don't like that we now instruct users to ignore warnings.

**Comment by turing85** [comment] 2022-11-03 13:46
> Thanks a lot @turing85 and now it is much clearer. I can understand the motivation to have `ShadowRuntimeConfigs` at build time. Good job! Is there any chance to improve it on Quarkus side as David mentioned in the discussion? I think it is worthy to reopen [quarkusio/quarkus#28415](https://github.com/quarkusio/quarkus/issues/28415)

I wrote a mail to quarkus-dev about this. For now,  I think, we are stuck with the workaround.

**Comment by turing85** [comment] 2022-11-03 13:49
> If we fix it in Quarkus we still have the use the old way if we want to support older versions of Quarkus.
> 
> What if we make `enabled` for all named configurations mandatory and use the same approach as DataSource? I don't like that we now instruct users to ignore warnings.

I think that this behaviour is not very user-friendly. Users would have to explicitly set `enabled` on *all* configurations, even if other properties are already set.

**Comment by middagj** [comment] 2022-11-03 15:13
True, let's keep it for now since it is working anyways. Hopefully we can fix it in Quarkus.

**Closed** 2022-11-03 16:15 UTC

**Comment by turing85** [comment] 2022-11-03 16:39
Release `2.0.1` is on its way. Expect it to be available within the next 4-6 hours.
